"""create n to m relationship between user and ingredients

Revision ID: f3bc232f2ca7
Revises: fad19a542bcb
Create Date: 2025-10-03 21:14:56.466550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3bc232f2ca7'
down_revision: Union[str, Sequence[str], None] = 'fad19a542bcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
